### ISSUE TITLE
Release ipyelk 0.2.1

### ISSUE THREAD

**Issue by dfreeman06** [jupyrdf/ipyelk#49]
It's time for another ipyelk release!

- [x] bug fixes
  - [x] #46 correctly merge elk element properties
  - [x] #48 label improvements, css text sizing, custom label key
- [x] infrastructure
  - [x] #52 stubbing out unit tests
- [x] update changelog
- [x] pick a funny new deer species
  - current front-runner is  [`Rangifer tarandus`](https://en.wikipedia.org/wiki/Reindeer)
- [x] tag
- [x] release on
  - [x] pypi
  - [x] npm
- [x] handle conda-forge update
- [ ] update [release procedure](https://github.com/jupyrdf/ipyelk/blob/master/CONTRIBUTING.md#releasing) with lessons learned
- [ ] bump to next working version
